tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/gui"
tap "homebrew/services"
brew "gdbm"
brew "libyaml"
brew "openssl"
brew "readline"
brew "xz"
brew "ansible"
brew "bash"
brew "bash-completion", link: false
brew "bdw-gc"
brew "boost-build"
brew "gettext"
brew "libffi"
brew "pixman"
brew "chruby", link: false
brew "cmake"
brew "coreutils"
brew "crystal"
brew "ffmpeg"
brew "fish"
brew "jpeg"
brew "git", link: false
brew "git-extras", link: false
brew "go"
brew "icu4c"
brew "heroku"
brew "hivemind"
brew "libcroco"
brew "libtool"
brew "imagemagick", args: ["with-librsvg"]
brew "intltool"
brew "jpegoptim"
brew "mysql"
brew "optipng"
brew "postgresql", link: false
brew "protobuf"
brew "redis", restart_service: true
brew "ruby-install", link: false
brew "s3cmd"
brew "telnet"
brew "tree"
brew "wget"
brew "yarn"
brew "zopfli"
cask "android-studio"
cask "font-fira-code"
cask "font-hasklig"
cask "font-ibm-plex"
cask "font-open-sans"
cask "gimp"
cask "inkscape"
cask "keepassxc"
cask "keka"
cask "krita"
cask "libreoffice"
cask "r-app"
cask "rstudio"
cask "virtualbox"
cask "visual-studio-code"
