tap "homebrew/core"
tap "homebrew/gui"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/fonts"
tap "caskroom/cask"
brew "libyaml"
brew "gdbm"
brew "readline"
brew "ansible"
brew "bash"
brew "bash-completion", link: false
brew "bdw-gc"
brew "boost-build"
brew "gettext"
brew "libffi"
brew "pcre"
brew "pixman"
brew "chruby", link: false
brew "cmake"
brew "coreutils"
brew "crystal-lang"
brew "git", link: false
brew "ffmpeg"
brew "jpeg"
brew "git-extras", link: false
brew "go"
brew "icu4c"
brew "heroku"
brew "hivemind"
brew "libcroco"
brew "libtool"
brew "xz"
brew "imagemagick", args: ["with-librsvg"]
brew "intltool"
brew "jpegoptim"
brew "mysql"
brew "optipng"
brew "postgresql", link: false
brew "protobuf"
brew "redis", restart_service: true
brew "ruby-install", link: false
brew "s3cmd"
brew "telnet"
brew "tree"
brew "wget"
brew "yarn"
brew "zopfli"
