#export JAVA_HOME="/usr/java/jdk1.6.0_20"
export GROOVY_HOME="$HOME/Libraries/groovy-1.7.2"
export GRAILS_HOME="$HOME/Libraries/grails-1.3.0"
export SCALA_HOME="$HOME/Libraries/scala-2.8.0.RC2"
export GWT_HOME="$HOME/Libraries/gwt-2.0.3"
export PATH="$JAVA_HOME/bin:$GROOVY_HOME/bin:$GRAILS_HOME/bin:$SCALA_HOME/bin:$PATH:$NARWHAL/bin:$GWT_HOME"
